(function(){
  const dict={
    ar:{name:'العربية',dir:'rtl',store:'بازار',tag:'اختياراتك في مكان واحد',search:'ابحث عن منتج...',cart:'السلة',track:'تتبع الطلب',login:'تسجيل الدخول',logout:'خروج',buyer:'حساب مشتري',seller:'حساب بائع',newBuyer:'إنشاء حساب مشتري جديد',newSeller:'إنشاء حساب بائع جديد',email:'البريد الإلكتروني',password:'كلمة المرور',fullName:'الاسم الكامل',phone:'رقم الجوال',address:'العنوان',storeName:'اسم المتجر',create:'إنشاء الحساب',sellerPending:'حساب البائع يخضع للمراجعة والموافقة قبل تفعيل البيع.',back:'العودة إلى المتجر',home:'الرئيسية',products:'المنتجات',categories:'التصنيفات',settings:'الإعدادات',orders:'الطلبات',sellers:'البائعون',security:'سجل الأمان',myProducts:'منتجاتي',myOrders:'طلبات منتجاتي',storeData:'بيانات المتجر',language:'اللغة',welcome:'مرحبًا بك في بازار',loginSuccess:'تم تسجيل الدخول بنجاح'},
    en:{name:'English',dir:'ltr',store:'Bazar',tag:'Your choices in one place',search:'Search products...',cart:'Cart',track:'Track order',login:'Sign in',logout:'Sign out',buyer:'Buyer account',seller:'Seller account',newBuyer:'Create new buyer account',newSeller:'Create new seller account',email:'Email',password:'Password',fullName:'Full name',phone:'Phone number',address:'Address',storeName:'Store name',create:'Create account',sellerPending:'Seller accounts are reviewed and approved before selling.',back:'Back to store',home:'Home',products:'Products',categories:'Categories',settings:'Settings',orders:'Orders',sellers:'Sellers',security:'Security log',myProducts:'My products',myOrders:'My orders',storeData:'Store profile',language:'Language',welcome:'Welcome to Bazar',loginSuccess:'Signed in successfully'},
    fa:{name:'فارسی',dir:'rtl',store:'بازار',tag:'انتخاب‌های شما در یک جا',search:'جستجوی محصول...',cart:'سبد خرید',track:'پیگیری سفارش',login:'ورود',logout:'خروج',buyer:'حساب خریدار',seller:'حساب فروشنده',newBuyer:'ایجاد حساب خریدار جدید',newSeller:'ایجاد حساب فروشنده جدید',email:'ایمیل',password:'رمز عبور',fullName:'نام کامل',phone:'شماره موبایل',address:'آدرس',storeName:'نام فروشگاه',create:'ایجاد حساب',sellerPending:'حساب‌های فروشنده پیش از فعال شدن فروش بررسی و تأیید می‌شوند.',back:'بازگشت به فروشگاه',home:'خانه',products:'محصولات',categories:'دسته‌بندی‌ها',settings:'تنظیمات',orders:'سفارش‌ها',sellers:'فروشندگان',security:'گزارش امنیتی',myProducts:'محصولات من',myOrders:'سفارش‌های من',storeData:'اطلاعات فروشگاه',language:'زبان',welcome:'به بازار خوش آمدید',loginSuccess:'ورود با موفقیت انجام شد'},
    prs:{name:'دری',dir:'rtl',store:'بازار',tag:'انتخاب‌های شما در یک جا',search:'جستجوی محصول...',cart:'سبد خرید',track:'پیگیری سفارش',login:'ورود',logout:'خروج',buyer:'حساب خریدار',seller:'حساب فروشنده',newBuyer:'ایجاد حساب خریدار جدید',newSeller:'ایجاد حساب فروشنده جدید',email:'ایمیل',password:'رمز عبور',fullName:'نام کامل',phone:'شماره تماس',address:'آدرس',storeName:'نام فروشگاه',create:'ایجاد حساب',sellerPending:'حساب فروشنده پیش از فعال شدن نیاز به بررسی و تأیید مدیریت دارد.',back:'بازگشت به فروشگاه',home:'صفحه اصلی',products:'محصولات',categories:'دسته‌بندی‌ها',settings:'تنظیمات',orders:'سفارش‌ها',sellers:'فروشندگان',security:'گزارش امنیتی',myProducts:'محصولات من',myOrders:'سفارش‌های من',storeData:'مشخصات فروشگاه',language:'زبان',welcome:'به بازار خوش آمدید',loginSuccess:'ورود موفق بود'},
    ps:{name:'پښتو',dir:'rtl',store:'بازار',tag:'ستاسو انتخابونه په یوه ځای کې',search:'محصول ولټوئ...',cart:'سبد',track:'د فرمایش تعقیب',login:'ننوتل',logout:'وتل',buyer:'د پېرودونکي حساب',seller:'د پلورونکي حساب',newBuyer:'نوی پېرودونکي حساب جوړول',newSeller:'نوی پلورونکي حساب جوړول',email:'برېښنالیک',password:'پټنوم',fullName:'بشپړ نوم',phone:'د موبایل شمېره',address:'پته',storeName:'د پلورنځي نوم',create:'حساب جوړول',sellerPending:'د پلورونکي حساب د فعالېدو مخکې د مدیریت له خوا ارزول او تاییدېږي.',back:'پلورنځي ته ستنېدل',home:'کور',products:'محصولات',categories:'کټګورۍ',settings:'تنظیمات',orders:'سپارښتنې',sellers:'پلورونکي',security:'امنیتي ثبت',myProducts:'زما محصولات',myOrders:'زما سپارښتنې',storeData:'د پلورنځي معلومات',language:'ژبه',welcome:'بازار ته ښه راغلاست',loginSuccess:'په بریالیتوب ننوتل'}
  };
  window.BazaarI18n={dict, get(){return localStorage.getItem('bazaar_lang')||'ar'}, set(l){if(!dict[l])l='ar';localStorage.setItem('bazaar_lang',l);apply(l);}, t(k){const l=this.get();return (dict[l]&&dict[l][k])||dict.ar[k]||k}, apply(l){const d=dict[l]||dict.ar;document.documentElement.lang=l;document.documentElement.dir=d.dir;document.querySelectorAll('[data-i18n]').forEach(e=>{const k=e.dataset.i18n;if(d[k])e.textContent=d[k]});document.querySelectorAll('[data-i18n-placeholder]').forEach(e=>{const k=e.dataset.i18nPlaceholder;if(d[k])e.placeholder=d[k]});const s=document.getElementById('bazaarLang');if(s)s.value=l;}};
  window.addEventListener('DOMContentLoaded',()=>BazaarI18n.apply(BazaarI18n.get()));
})();
